name: Feature Request
description: Suggest a new tool, capability, or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Feature requests are welcome. Please describe the problem you're trying to solve, not just the solution — it helps us find the right approach.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      placeholder: "Right now, there's no way to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: "A new tool `X` that..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      placeholder: "I tried using `search_memory` for this but..."

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else — links, prior art, example use cases.
